export default {
  'action.devices.commands.BrightnessAbsolute': 'Brightness',
  'action.devices.commands.GetCameraStream': 'CameraStream',
  'action.devices.commands.ColorAbsolute': 'ColorSetting',
  'action.devices.commands.Dock': 'Dock',
  'action.devices.commands.SetFanSpeed': 'FanSpeed',
  'action.devices.commands.Reverse': 'FanSpeed',
  'action.devices.commands.Locate': 'Locator',
  'action.devices.commands.SetModes': 'Modes',
  'action.devices.commands.OnOff': 'OnOff',
  'action.devices.commands.ActivateScene': 'Scene',
  'action.devices.commands.StartStop': 'StartStop',
  'action.devices.commands.PauseUnpause': 'StartStop',
  'action.devices.commands.SetTemperature': 'TemperatureControl',
  'action.devices.commands.ThermostatTemperatureSetpoint': 'TemperatureSetting',
  'action.devices.commands.ThermostatTemperatureSetRange': 'TemperatureSetting',
  'action.devices.commands.ThermostatSetMode': 'TemperatureSetting',
  'action.devices.commands.SetToggles': 'Toggles',
};
