export default {
  ACUnit: 'action.devices.types.AC_UNIT',
  AirPurifier: 'action.devices.types.AIRPURIFIER',
  Camera: 'action.devices.types.CAMERA',
  CoffeeMaker: 'action.devices.types.COFFEE_MAKER',
  DishWasher: 'action.devices.types.DISHWASHER',
  Dryer: 'action.devices.types.DRYER',
  Fan: 'action.devices.types.FAN',
  Kettle: 'action.devices.types.KETTLE',
  Light: 'action.devices.types.LIGHT',
  Outlet: 'action.devices.types.OUTLET',
  Oven: 'action.devices.types.OVEN',
  Refrigerator: 'action.devices.types.REFRIGERATOR',
  Scene: 'action.devices.types.SCENE',
  Sprinkler: 'action.devices.types.SPRINKLER',
  Switch: 'action.devices.types.SWITCH',
  Thermostat: 'action.devices.types.THERMOSTAT',
  Vacuum: 'action.devices.types.VACUUM',
  Washer: 'action.devices.types.WASHER',
};
