query Widgets {
    widgets {
        id
        __typename
        ... on SensorWidget {
            name
            dataType
        }
        ... on RemoteControllerWidget {
            controllerId
        }
        ... on DeviceWidget {
            deviceId
        }
    }
}
