{
    user {
        username
        devices {
            id
            type
            defaultNames
            name
            nicknames
            traits {
                type
                info
                state
            }
        }
    }
}
