mutation AddDevice($device: InputDevice!) {
    addDevice(device: $device) {
        id
        type
        name
        defaultNames
        nicknames
        traits {
            type
            info
            state
        }
    }
}
